### PR TITLE
Introduce new request_user decorator to check for a specific user

### PR DESCRIPTION
**Pull request by max-k**
I also made some improvements to satisfy pylint.

### CODE REVIEW

**Comment by max-k** [comment]
Hi, do you plan to make a new release which ships this improvement ?

**Comment by COUR4G3** [comment]
Was in the process of making a release yesterday and got sidetracked. Will probably in the next hour.

**Comment by max-k** [comment]
Thank you very much.

**Comment by COUR4G3** [comment]
Unable to upload on my dev machine at work for some reason. Will try at home later.

**Comment by COUR4G3** [comment]
Latest version uploaded, sorry it took so long, can't seem to update setuptools on my dev machine at work so had to do it from home.

**Comment by max-k** [comment]
No problem. Thank you.

**Pull request merged**
